name: Pipeline CI

# Este pipeline se ejecuta cada vez que se hace un push a la rama main. 
on:
  push:
    branches:
      - main

jobs:
  # Se encarga de ejecutar los tests y construir el proyecto.
  test-and-build:
    # Crea una máquina virtual con Ubuntu 
    runs-on: ubuntu-latest

    steps:
      # Descarga el código del repo
      - name: Descargar repositorio
        uses: actions/checkout@v4

      # Instala node en la MV (misma versión que se usa en el proyecto)
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Instala las dependencias del proyecto
      - name: Instalar dependencias
        run: npm install

      # Ejecuta los tests definidos en el proyecto
      - name: Ejecutar tests
        run: npm test
      
      # Construye el proyecto
      - name: Deploy en Render
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"

      # Notificación de éxito
      - name: Notificar éxito en Slack
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\":\"✅ Pipeline exitoso

          Usuario: ${{ github.actor }}
           Commit: ${{ github.event.head_commit.message }}
          \"
          }" \
          "${{ secrets.SLACK_WEBHOOK_URL }}"
  

      # Notificación de error
      - name: Notificar fallo en Slack
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\":\"❌ Pipeline con fallo

        Usuario: ${{ github.actor }}
        Commit: ${{ github.event.head_commit.message }}

        Revisar: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          \"
           }" \
           "${{ secrets.SLACK_WEBHOOK_URL }}"
