name: Pipeline CI

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    # crea una máquina virtual con Ubuntu 
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar linter
        run: npm run lint

      - name: Ejecutar tests
        run: npm test
      
      - name: Deploy en Render
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"

      - name: Notificar éxito en Slack
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_ACTOR: ${{ github.actor }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          payload=$(node -e 'console.log(JSON.stringify({ text: `✅ Pipeline exitoso\n\nUsuario: ${process.env.GITHUB_ACTOR}\nCommit: ${process.env.COMMIT_MESSAGE}` }))')
          curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"
  

      - name: Notificar fallo en Slack
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_ACTOR: ${{ github.actor }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          payload=$(node -e 'console.log(JSON.stringify({ text: `❌ Pipeline con fallo\n\nUsuario: ${process.env.GITHUB_ACTOR}\nCommit: ${process.env.COMMIT_MESSAGE}\n\nRevisar: ${process.env.RUN_URL}` }))')
          curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"
